default_platform(:ios)

platform :ios do
	desc "Run all unit tests for Youse Challange App"
	lane :test do
		scan(scheme: "Youse-Challenge", devices: ["iPhone 8 Plus"])
	end

	desc "Display test coverage report using slather"
	lane :coverage do
		sh("mkdir -p CoverageOutput")
		slather(
            scheme: "Youse-Challenge",
            workspace: "Youse-Challenge.xcworkspace",
            proj: "Youse-Challenge.xcodeproj",
            html: true,
            show: true,
            output_directory:"CoverageOutput"
        )
	end
end
